# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author_profile',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='photos.Profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='images/beagle.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
